task-03-accordion-solution
js-tasks-ru/htmlcss-20220519_vasilisa-zaytseva pull request #4
Opened 2022-06-10 01:31 UTC by vasilisa-za

Есть несколько вопросов: 
1) я скопировала стрелку из figma как png файл, так нужно было делать или как-то по-другому самим ее рисовать?
2)  в качестве крнтейнера accordion я взяла div, в который помещаются accordin__items, но в figma есть еще как бы подложка - div размером 1440x495, его тоже надо было верстать?

2022-06-10 01:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-10 01:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-10 01:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-10 18:37 UTC, GSemikozov requested changes

2022-06-10 18:37 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    position: absolute;
на уровне блока внешнее позиционирование не задаем, поэтому все свойства кроме font-family можно удалить

2022-06-10 18:37 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
ширину жестко фиксировать тоже не надо

2022-06-10 18:37 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details summary::-webkit-details-marker {
отсюда и ниже вдруг перестали использовать БЭМ-классы - надо поправить)

2022-06-12 01:52 UTC, vasilisa-za commented on 03-lection1/02-accordion/accordion.css
> +details summary::-webkit-details-marker {
имеется в виду, что вместо тегов details и summary использовать классы, которые были им присвоены - .accordion__item и .accordion__title соответственно?

2022-06-13 10:34 UTC, GSemikozov approved these changes

2022-06-13 10:34 UTC, merged