main-page-layout-solution
js-tasks-ru/htmlcss-20220519_vasilisa-zaytseva pull request #5
Opened 2022-06-12 01:43 UTC by vasilisa-za

Некоторые вопросы:
1)Не поняла, какой стиль задавать классу page
2) Нужно ли использовать container, который использовали для header, для footer?
3) Классу preview я задала фиксированную высоту, подозреваю, что это неправильно, но иначе header налипает на footer

2022-06-12 01:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-12 01:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-13 10:34 UTC, GSemikozov requested changes

2022-06-13 10:34 UTC, GSemikozov commented on components/footer/footer.css
> +    padding: 72px 400px 136px;
слева-справа не надо, у нас ведь есть container )

2022-06-13 16:23 UTC, vasilisa-za commented on components/footer/footer.css
> +    padding: 72px 400px 136px;
поправила

2022-06-17 20:56 UTC, GSemikozov commented
> 

1. имеется в виду в целом для выравнивания вложенных блоков? или стилистическое оформление (фон/цвет текст)? Если первое - то скорее всего надо растянуть на 100% высоты + если используем флексы, то сделать флекс-контейнером с flex-direction: column
2. да, конечно, контейнер - это общий переиспользуемый блок
3. это связано с первым вопросом - если мы используем флекс или грид, то можно взять реализацию "прижатый к низу экрана футер" из лекций

2022-06-25 19:16 UTC, GSemikozov requested changes

2022-06-25 19:16 UTC, GSemikozov commented on components/preview/preview.css
> +    width: calc(100%/3 - 30px);
скорее так: `width: calc(100% / 3 - 30 * 2 / 3 )`

2022-07-10 08:54 UTC, GSemikozov approved these changes

2022-07-10 08:54 UTC, merged